spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #driver-class-name: com.mysql.jdbc.Driver
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      #url: jdbc:mysql://localhost:3306/report?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      url: jdbc:sqlserver://172.17.97.22:1433;DatabaseName=PMC
      username: MesQAT
      password: MesQAT01
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

##多数据源的配置，需要引用pmc_report_datasource
dynamic:
  datasource:
    slave1:
      #driver-class-name: oracle.jdbc.OracleDriver
      #url: jdbc:oracle:thin:@172.17.97.23:1521:ORAMESQ
      #username: MES_RD_OL
      #password: MesReadOnly123
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@172.18.254.70:1521:ORAMESO
      username: mes_ods
      password: 2QZjRqTj4kLT
      validation-query: SELECT 1 FROM DUAL
#    slave2:
#      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#      url: jdbc:sqlserver://172.17.97.22:1433;DatabaseName=PMC
#      username: MesQAT
#      password: MesQAT01
#    slave3:
#      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#      url: jdbc:sqlserver://172.18.4.121:1433;DatabaseName=BIW3
#      username: PMC_REPORT_BIW3
#      password: P@ssw0rd
##多数据源的配置，需要引用pmc_report_datasource
#dynamic:
#  datasource:
#    slave2:
#      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#      url: jdbc:sqlserver://172.17.97.22:1433;DatabaseName=PMC
#      username: MesQAT
#      password: MesQAT01
#    slave2:
#      driver-class-name: org.postgresql.Driver
#      url: jdbc:postgresql://localhost:5432/report
#      username: root
#      password: 1234