server:
  port: 8089
  servlet:
    context-path: /gean-generator


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL配置
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/report?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    username: root
#    password: 1234
    #oracle配置
#    driverClassName: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@192.168.1.4:1521/XE
#    username: system
#    password: 1234
    #SQLServer配置
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://172.17.97.22:1433;DatabaseName=PMC
    username: MesQAT
    password: MesQAT01
    #PostgreSQL配置
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://192.168.10.10:5432/表空间
#    username: postgres
#    password: 123456
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: classpath:/static/,classpath:/views/


mybatis:
  mapperLocations: classpath:mapper/**/*.xml


pagehelper:
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


#指定数据库，可选值有【mysql、oracle、sqlserver、postgresql】
gean:
  database: sqlserver